# -*- coding: utf-8 -*-
"""Assignment-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMENTcIBPUhNmcwbn1aF1UNkzvWeS-2n
"""

#1
#Aim:To write a Python program to add two numbers entered by the user.
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
sum = num1 + num2
print("The sum is:", sum)

#2
#Aim:To write a Python program to interchange the values of two variables.
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
a, b = b, a
print("After swapping:")
print("a =", a)
print("b =", b)

#3
#Aim:To write a Python program to find the largest among three numbers using conditional statements.
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))
if a >= b and a >= c:
    print("Largest number is:", a)
elif b >= a and b >= c:
    print("Largest number is:", b)
else:
    print("Largest number is:", c)

#4
#Aim:To write a Python program to check whether a given number is even or odd.
num = int(input("Enter a number: "))
if num % 2 == 0:
    print("Even")
else:
    print("Odd")

#5
#To write a Python program to determine whether a number is positive, negative,or zero.
num = float(input("Enter a number: "))
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

#6
#Aim:To write a Python program to check whether a given year is a leap year.
year = int(input("Enter a year: "))
if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
    print("Leap Year")
else:
    print("Not a Leap Year")

#7
#Aim:To write a Python program to perform basic arithmetic operations using operators.
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)

#8
#Aim:To write a Python program to display the multiplication table of a given number.
num = int(input("Enter a number: "))
for i in range(1, 11):
    print(num, "x", i, "=", num * i)

#9
#Aim:To write a Python program to calculate the factorial of a number using a loop.
num = int(input("Enter a number: "))
fact = 1
for i in range(1, num + 1):
    fact *= i
print("Factorial =", fact)

#10
#Aim:To write a Python program to find the sum of the first N natural numbers.
n = int(input("Enter Number: "))
sum = 0
for i in range(1, n + 1):
    sum += i
print("Sum =", sum)

#11
#Aim:To write a Python program to print numbers from 1 to N using a for loop.
n = int(input("Enter Number: "))
for i in range(1, n + 1):
    print(i)

#12
#Aim:To write a Python program to print numbers in reverse order from N to 1.
n = int(input("Enter Number: "))
for i in range(n, 0, -1):
    print(i)

#13
#Aim:To write a Python program to print all even numbers up to a given limit.
n = int(input("Enter Number: "))
for i in range(1, n + 1):
    if i % 2 == 0:
        print(i)

#14
#To write a Python program to reverse the digits of a given number.
n = int(input("Enter a number: "))
r = 0
while n > 0:
    d = n % 10
    r = r * 10 + d
    n //= 10
print("Reversed number =", r)

#15
#Aim:To write a Python program to count the number of digits in a given integer.
n = int(input("Enter a number: "))
c = 0
while n > 0:
    n //= 10
    c += 1
print("Number of digits =", c)

#16
#Aim:To write a Python program to calculate the sum of digits of a given number.
n = int(input("Enter a number: "))
s = 0
while n > 0:
    d = n % 10
    s += d
    n //= 10
print("Sum of digits =", s)

#17
#Aim:To write a Python program to check whether a given number is prime.
num = int(input("Enter a number: "))
if num > 1:
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            print("Not Prime")
            break
    else:
        print("Prime")
else:
    print("Not Prime")

#18
#Aim:To write a Python program to generate the Fibonacci series up to N terms.
n = int(input("Enter the number of terms: "))
a, b = 0, 1
print("Fibonacci series:")
for i in range(n):
    print(a)
    a, b = b, a + b

#19
#Aim:To write a Python program to check whether a string is a palindrome.
s = input("Enter a string: ")
if s == s[::-1]:
    print("Palindrome")
else:
    print("Not a Palindrome")

#20
#Aim:To write a Python program to check whether a given number is an Armstrong number.
n = int(input("Enter a number: "))
t = n
ds = len(str(n))
s = 0
while t > 0:
    d = t % 10
    s += d ** ds
    t //= 10
if s == n:
    print("Armstrong Number")
else:
    print("Not an Armstrong Number")